title: monad
description: Federated semantic compute runtime.
url: https://neurons-me.github.io
baseurl: "/monad"

remote_theme: neurons-me/neurons-me

plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false

exclude:
  - Typescript/node_modules
  - Typescript/dist
  - Typescript/src
  - Typescript/tests
  - Typescript/scripts
  - node_modules
  - "*/node_modules"
  - vendor

me_theme:
  brand: monad
  nav:
    - label: Home
      url: https://neurons-me.github.io/
    - label: Github
      url: https://github.com/neurons-me
    - label: All.This
      url: https://neurons-me.github.io/all.this/
