export interface PublicFigureSeed {
  username: string;
  name: string;
  field: string;
  birthDate: string;
  deathDate?: string | null;
  origin: string;
  father?: string | null;
  mother?: string | null;
}

export const PUBLIC_FIGURES_PASSWORD = "orwell1984";

export const PUBLIC_FIGURES: PublicFigureSeed[] = [
  {
    username: "ada-lovelace",
    name: "Ada Lovelace",
    field: "computing",
    birthDate: "1815-12-10",
    deathDate: "1852-11-27",
    origin: "London, England",
    father: "George Gordon Byron",
    mother: "Anne Isabella Milbanke",
  },
  {
    username: "alan-turing",
    name: "Alan Turing",
    field: "computing",
    birthDate: "1912-06-23",
    deathDate: "1954-06-07",
    origin: "London, England",
    father: "Julius Mathison Turing",
    mother: "Ethel Sara Stoney",
  },
  {
    username: "albert-einstein",
    name: "Albert Einstein",
    field: "physics",
    birthDate: "1879-03-14",
    deathDate: "1955-04-18",
    origin: "Ulm, German Empire",
    father: "Hermann Einstein",
    mother: "Pauline Koch",
  },
  {
    username: "marie-curie",
    name: "Marie Curie",
    field: "chemistry",
    birthDate: "1867-11-07",
    deathDate: "1934-07-04",
    origin: "Warsaw, Poland",
    father: "Wladyslaw Sklodowski",
    mother: "Bronislawa Boguska",
  },
  {
    username: "nikola-tesla",
    name: "Nikola Tesla",
    field: "engineering",
    birthDate: "1856-07-10",
    deathDate: "1943-01-07",
    origin: "Smiljan, Austrian Empire",
    father: "Milutin Tesla",
    mother: "Georgina Duka",
  },
  {
    username: "isaac-newton",
    name: "Isaac Newton",
    field: "physics",
    birthDate: "1643-01-04",
    deathDate: "1727-03-31",
    origin: "Woolsthorpe-by-Colsterworth, England",
    father: "Isaac Newton Sr.",
    mother: "Hannah Ayscough",
  },
  {
    username: "charles-darwin",
    name: "Charles Darwin",
    field: "biology",
    birthDate: "1809-02-12",
    deathDate: "1882-04-19",
    origin: "Shrewsbury, England",
    father: "Robert Darwin",
    mother: "Susannah Wedgwood",
  },
  {
    username: "galileo-galilei",
    name: "Galileo Galilei",
    field: "astronomy",
    birthDate: "1564-02-15",
    deathDate: "1642-01-08",
    origin: "Pisa, Duchy of Florence",
    father: "Vincenzo Galilei",
    mother: "Giulia Ammannati",
  },
  {
    username: "sigmund-freud",
    name: "Sigmund Freud",
    field: "psychology",
    birthDate: "1856-05-06",
    deathDate: "1939-09-23",
    origin: "Freiberg in Moravia, Austrian Empire",
    father: "Jacob Freud",
    mother: "Amalia Nathansohn",
  },
  {
    username: "steve-jobs",
    name: "Steve Jobs",
    field: "technology",
    birthDate: "1955-02-24",
    deathDate: "2011-10-05",
    origin: "San Francisco, California, United States",
    father: "Abdulfattah Jandali",
    mother: "Joanne Schieble",
  },
  {
    username: "bill-gates",
    name: "Bill Gates",
    field: "technology",
    birthDate: "1955-10-28",
    deathDate: null,
    origin: "Seattle, Washington, United States",
    father: "William H. Gates Sr.",
    mother: "Mary Maxwell Gates",
  },
  {
    username: "martin-luther-king-jr",
    name: "Martin Luther King Jr.",
    field: "civil-rights",
    birthDate: "1929-01-15",
    deathDate: "1968-04-04",
    origin: "Atlanta, Georgia, United States",
    father: "Martin Luther King Sr.",
    mother: "Alberta Williams King",
  },
  {
    username: "rosa-parks",
    name: "Rosa Parks",
    field: "civil-rights",
    birthDate: "1913-02-04",
    deathDate: "2005-10-24",
    origin: "Tuskegee, Alabama, United States",
    father: "James McCauley",
    mother: "Leona Edwards",
  },
  {
    username: "nelson-mandela",
    name: "Nelson Mandela",
    field: "politics",
    birthDate: "1918-07-18",
    deathDate: "2013-12-05",
    origin: "Mvezo, South Africa",
    father: "Gadla Henry Mphakanyiswa",
    mother: "Nosekeni Fanny",
  },
  {
    username: "mahatma-gandhi",
    name: "Mahatma Gandhi",
    field: "politics",
    birthDate: "1869-10-02",
    deathDate: "1948-01-30",
    origin: "Porbandar, India",
    father: "Karamchand Gandhi",
    mother: "Putlibai Gandhi",
  },
  {
    username: "abraham-lincoln",
    name: "Abraham Lincoln",
    field: "politics",
    birthDate: "1809-02-12",
    deathDate: "1865-04-15",
    origin: "Sinking Spring Farm, Kentucky, United States",
    father: "Thomas Lincoln",
    mother: "Nancy Hanks Lincoln",
  },
  {
    username: "winston-churchill",
    name: "Winston Churchill",
    field: "politics",
    birthDate: "1874-11-30",
    deathDate: "1965-01-24",
    origin: "Blenheim Palace, England",
    father: "Lord Randolph Churchill",
    mother: "Jennie Jerome",
  },
  {
    username: "simon-bolivar",
    name: "Simon Bolivar",
    field: "politics",
    birthDate: "1783-07-24",
    deathDate: "1830-12-17",
    origin: "Caracas, Venezuela",
    father: "Juan Vicente Bolivar y Ponte",
    mother: "Maria de la Concepcion Palacios y Blanco",
  },
  {
    username: "frida-kahlo",
    name: "Frida Kahlo",
    field: "art",
    birthDate: "1907-07-06",
    deathDate: "1954-07-13",
    origin: "Coyoacan, Mexico City, Mexico",
    father: "Guillermo Kahlo",
    mother: "Matilde Calderon y Gonzalez",
  },
  {
    username: "pablo-picasso",
    name: "Pablo Picasso",
    field: "art",
    birthDate: "1881-10-25",
    deathDate: "1973-04-08",
    origin: "Malaga, Spain",
    father: "Jose Ruiz y Blasco",
    mother: "Maria Picasso y Lopez",
  },
  {
    username: "gabriel-garcia-marquez",
    name: "Gabriel Garcia Marquez",
    field: "literature",
    birthDate: "1927-03-06",
    deathDate: "2014-04-17",
    origin: "Aracataca, Colombia",
    father: "Gabriel Eligio Garcia",
    mother: "Luisa Santiaga Marquez Iguaran",
  },
  {
    username: "oscar-wilde",
    name: "Oscar Wilde",
    field: "literature",
    birthDate: "1854-10-16",
    deathDate: "1900-11-30",
    origin: "Dublin, Ireland",
    father: "William Wilde",
    mother: "Jane Francesca Elgee",
  },
  {
    username: "jane-austen",
    name: "Jane Austen",
    field: "literature",
    birthDate: "1775-12-16",
    deathDate: "1817-07-18",
    origin: "Steventon, England",
    father: "George Austen",
    mother: "Cassandra Leigh",
  },
  {
    username: "wolfgang-amadeus-mozart",
    name: "Wolfgang Amadeus Mozart",
    field: "music",
    birthDate: "1756-01-27",
    deathDate: "1791-12-05",
    origin: "Salzburg, Holy Roman Empire",
    father: "Leopold Mozart",
    mother: "Anna Maria Pertl",
  },
  {
    username: "freddie-mercury",
    name: "Freddie Mercury",
    field: "music",
    birthDate: "1946-09-05",
    deathDate: "1991-11-24",
    origin: "Stone Town, Zanzibar",
    father: "Bomi Bulsara",
    mother: "Jer Bulsara",
  },
  {
    username: "juan-gabriel",
    name: "Juan Gabriel",
    field: "music",
    birthDate: "1950-01-07",
    deathDate: "2016-08-28",
    origin: "Paracuaro, Michoacan, Mexico",
    father: "Gabriel Aguilera Rodriguez",
    mother: "Victoria Valadez Rojas",
  },
  {
    username: "david-bowie",
    name: "David Bowie",
    field: "music",
    birthDate: "1947-01-08",
    deathDate: "2016-01-10",
    origin: "London, England",
    father: "Haywood Stenton Jones",
    mother: "Margaret Mary Burns",
  },
  {
    username: "charlie-chaplin",
    name: "Charlie Chaplin",
    field: "cinema",
    birthDate: "1889-04-16",
    deathDate: "1977-12-25",
    origin: "London, England",
    father: "Charles Chaplin Sr.",
    mother: "Hannah Chaplin",
  },
  {
    username: "audrey-hepburn",
    name: "Audrey Hepburn",
    field: "cinema",
    birthDate: "1929-05-04",
    deathDate: "1993-01-20",
    origin: "Ixelles, Belgium",
    father: "Joseph Victor Anthony Ruston",
    mother: "Ella van Heemstra",
  },
  {
    username: "marilyn-monroe",
    name: "Marilyn Monroe",
    field: "cinema",
    birthDate: "1926-06-01",
    deathDate: "1962-08-04",
    origin: "Los Angeles, California, United States",
    father: null,
    mother: "Gladys Pearl Baker",
  },
  {
    username: "michael-jordan",
    name: "Michael Jordan",
    field: "sports",
    birthDate: "1963-02-17",
    deathDate: null,
    origin: "Brooklyn, New York, United States",
    father: "James R. Jordan Sr.",
    mother: "Deloris Jordan",
  },
  {
    username: "muhammad-ali",
    name: "Muhammad Ali",
    field: "sports",
    birthDate: "1942-01-17",
    deathDate: "2016-06-03",
    origin: "Louisville, Kentucky, United States",
    father: "Cassius Marcellus Clay Sr.",
    mother: "Odessa Grady Clay",
  },
  {
    username: "pele",
    name: "Pele",
    field: "sports",
    birthDate: "1940-10-23",
    deathDate: "2022-12-29",
    origin: "Tres Coracoes, Brazil",
    father: "Joao Ramos do Nascimento",
    mother: "Celeste Arantes",
  },
  {
    username: "diego-maradona",
    name: "Diego Maradona",
    field: "sports",
    birthDate: "1960-10-30",
    deathDate: "2020-11-25",
    origin: "Lanus, Buenos Aires, Argentina",
    father: "Diego Maradona",
    mother: "Dalma Salvadora Franco",
  },
];
